superlists/lists/urls.py
from django.conf.urls import patterns, url
from lists import views

urlpatterns = patterns(
    url(
        r'^(\d+)/$',
        views.view_list,
        name='view_list'
    ),
    url(r'^new$', views.new_list, name='new_list'),
    url(
        r'^(\d+)/add_item$',
        views.add_item,
        name='add_item'
        ),
    url(
        r'^(\d+)/$',
        views.view_list,
        name='view_list'
    ),
    )

superlists/superlists/urls.py
from django.conf.urls import patterns, url, include
from lists import views

urlpatterns = patterns('',
                       url(r'^$', 'lists.views.home_page', name='home_page'),
                       url(r'^lists/', include('lists.urls')),
                       )

superlists/lists/models.py
from django.db import models


class List(models.Model):
    pass


class Item(models.Model):
    text = models.TextField()
    list = models.ForeignKey(List, default=None)

superlists/lists/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import redirect, render
from lists.models import Item, List


def home_page(request):
    return render(
        request,
        'lists/home.html',
    )


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    return render(request, 'lists/list.html', {'list': list_})


def new_list(request):
    list_ = List.objects.create()
    item = Item.objects.create(text=request.POST['item_text'], list=list_)
    try:
        item.full_clean()
        item.save()
    except ValidationError:
        list_.delete()
        error = "You can't have an empty list item"
        return render(request, 'lists/home.html', {'error': error})
    return redirect('/lists/%d/' % (list_.id))


def add_item(request, list_id):
    list_ = List.objects.get(id=list_id)
    Item.objects.create(
        text=request.POST['item_text'], list=list_
        )
    return redirect('/lists/%d/' % (list_.id))

superlists/lists/templates/lists/base.html
<html>
    <head>
        <title>To-Do lists</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <link href="/static/css/base.css" rel="stylesheet" media="screen">
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3 jumbotron">
                    <div class="text-center">
                        <h1>{% block header_text %}{% endblock %}</h1>
                        <form method="POST" action="{% block form_action %}{% endblock %}">
                            <input name="item_text" id="id_new_item" class="form-control input-lg" placeholder="Enter a to-do item" />
                            {% csrf_token %}
                            {% if error %}
                                <div class="form-group has-error">
                                    <span class="help-block">{{error}}</span>
                                </div>
                            {% endif %}
                        </form>
                        {% block table %}{% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

superlists/lists/templates/lists/home.html
{% extends "lists/base.html" %}
{% block header_text %}Start a new To-Do list{% endblock %}
{% block form_action%}/lists/new{% endblock %}

superlists/lists/templates/lists/list.html
{% extends "lists/base.html" %}
{% block header_text %}To-Do lists{% endblock %}
{% block form_action %}/lists/{{list.id}}/add_item{% endblock %}
{% block table %}
        <table id="id_list_table" class="table">
	    {% for item in list.item_set.all %}
	    <tr>
		    <td>{% if item.text%}{{forloop.counter}}: {{item.text}}{% endif %}</td>
	    </tr>
	    {% endfor %}
        </table>
{% endblock %}